```[
  {
      "player_key": 1404199176,
      "player_id": "1404199176",
      "player_image": "https://apiv3.apifootball.com/badges/players/58284_sergio-camus.jpg",
      "player_name": "Sergio Camus",
      "player_number": "",
      "player_country": "",
      "player_type": "Defenders",
      "player_age": "",
      "player_match_played": "16",
      "player_goals": "0",
      "player_yellow_cards": "2",
      "player_red_cards": "0",
      "player_minutes": "1191",
      "player_injured": "No",
      "player_substitute_out": "2",
      "player_substitutes_on_bench": "3",
      "player_assists": "",
      "player_is_captain": "",
      "player_shots_total": "",
      "player_goals_conceded": "",
      "player_fouls_committed": "",
      "player_tackles": "",
      "player_blocks": "",
      "player_crosses_total": "",
      "player_interceptions": "",
      "player_clearances": "",
      "player_dispossesed": "",
      "player_saves": "",
      "player_inside_box_saves": "",
      "player_duels_total": "",
      "player_duels_won": "",
      "player_dribble_attempts": "",
      "player_dribble_succ": "",
      "player_pen_comm": "",
      "player_pen_won": "",
      "player_pen_scored": "",
      "player_pen_missed": "",
      "player_passes": "",
      "player_passes_accuracy": "",
      "player_key_passes": "",
      "player_woordworks": "",
      "player_rating": "",
      "team_name": "Atlético Madrid II",
      "team_key": "7182"
  }
]```